version: '3.7'

services:
  school-service:
    image: xmrcmx/school-service:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - schooldb 

    networks:
      - school-network

  schooldb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: school
      MYSQL_DATABASE: school
  
    networks:
      - school-network  
  
networks:
  school-network: